# Site settings
title: Yichang's Blog
description: 'A personal blog for recording my life'
url: 'http://Yichang812.github.io/Blog' 
baseurl: '/Blog/'

#for local testing
#baseurl: '/'

google_analytics: 'UA-73369864-1'

author:
  name: 'Li Yichang'
  email: ariellee121@gmail.com
  github_username:  Yichang812
  linkedin_username: liyichang

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
