# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://Yichang812.github.io/Blog' 
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Li Yichang'
  email: ariellee121@gmail.com
  github_username:  Yichang812
  linkedin_username:  Li Yichang

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']